apiVersion: batch/v1
kind: Job
metadata:
  name: loadgenerator-job
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600   # Job will be deleted after 1 h of work
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: loadgenerator
      restartPolicy: Never
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: loadgenerator-logs-pvc
      initContainers:
      - name: init-logs
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
          - >
            mkdir -p /logs
        volumeMounts:
        - name: log-volume
          mountPath: /logs
      - name: frontend-check
        image: busybox:latest
        command:
          - /bin/sh
          - -exc
          - |
            MAX_RETRIES=12
            RETRY_INTERVAL=10
            for i in $(seq 1 $MAX_RETRIES); do
              echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
              STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
              if [ $STATUSCODE -eq 200 ]; then
                  echo "Frontend is reachable."
                  exit 0
              fi
              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
              sleep $RETRY_INTERVAL
            done
            echo "Failed to reach frontend after $MAX_RETRIES attempts."
            exit 1
        env:
        - name: FRONTEND_ADDR
          value: "frontend:80"
      containers:
      - name: main
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator:v0.10.3
        command: ["/bin/sh", "-c"]
        args:
          - >
            locust --host=http://${FRONTEND_ADDR} --headless -u 20 -r 2 --run-time 2h 2>&1 | tee /logs/locust_2h_highload.txt
        env:
        - name: FRONTEND_ADDR
          value: "frontend:80"
        - name: USERS
          value: "20"
        - name: RATE
          value: "2"
        volumeMounts:
        - name: log-volume
          mountPath: /logs
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
